name: Lint Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install flake8
        run: pip install flake8

      - name: Run Python linting
        working-directory: server
        run: flake8 . --ignore=E501,E302,E303,E231,E225,E226,E275,E265,E712,W293,W391,F401,F811,F841,E722

      - name: Python linting completed
        run: echo "Python linting completed successfully"

  lint_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install JSHint
        working-directory: server
        run: npm install jshint

      - name: Run JavaScript linting
        working-directory: server
        run: find database -name "*.js" -print0 | xargs -0 ./node_modules/.bin/jshint --config .jshintrc

      - name: JavaScript linting completed
        run: echo "JavaScript linting completed successfully"
